In [1]:
import torch
import numpy as np

In [10]:
# 텐서 초기화
data = [[1, 2],
        [3, 4]]
x_data = torch.tensor(data) # 데이터로부터 직접 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array) # array로부터 생성
# 다른 텐서로부터 생성
x_ones = torch.ones_like(x_data) # x_data의 속성 유지
print(f'Ones Tensor: \n{x_ones}')
x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성에 덮어쓰기
print(f'Random Tensor: \n{x_rand}')

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'Random Tensor: \n{rand_tensor}')
print(f'Ones Tensor: \n{ones_tensor}')
print(f'Zeros Tensor: \n{zeros_tensor}')

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])
Random Tensor: 
tensor([[0.3662, 0.4970],
        [0.6738, 0.2137]])
Random Tensor: 
tensor([[0.2342, 0.7316, 0.2233],
        [0.6071, 0.9586, 0.4900]])
Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# 텐서의 속성(Attribute)
tensor = torch.rand(3, 4)
print(f'Shape of tensor: \n{tensor.shape}')
print(f'Data type of tensor: \n{tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: 
torch.Size([3, 4])
Data type of tensor: 
torch.float32
Device tensor is stored on: cpu


In [17]:
# 텐서 연산(Operation)
if torch.cuda.is_available():
    tensor = tensor.to('cuda') # gpu가 존재하면 텐서 이동
tensor.device
torch.cuda.is_available()

False

In [21]:
# NumPy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print(tensor)
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[:, -1]}')


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [ ]:
# 텐서 합치기`