In [2]:
import torch
import numpy as np

In [3]:
# 텐서 초기화
data = [[1, 2],
        [3, 4]]
x_data = torch.tensor(data) # 데이터로부터 직접 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array) # array로부터 생성
# 다른 텐서로부터 생성
x_ones = torch.ones_like(x_data) # x_data의 속성 유지
print(f'Ones Tensor: \n{x_ones}')
x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성에 덮어쓰기
print(f'Random Tensor: \n{x_rand}')

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'Random Tensor: \n{rand_tensor}')
print(f'Ones Tensor: \n{ones_tensor}')
print(f'Zeros Tensor: \n{zeros_tensor}')

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])
Random Tensor: 
tensor([[0.3089, 0.1318],
        [0.3275, 0.8864]])
Random Tensor: 
tensor([[0.3572, 0.2399, 0.2541],
        [0.4700, 0.0953, 0.9705]])
Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# 텐서의 속성(Attribute)
tensor = torch.rand(3, 4)
print(f'Shape of tensor: \n{tensor.shape}')
print(f'Data type of tensor: \n{tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: 
torch.Size([3, 4])
Data type of tensor: 
torch.float32
Device tensor is stored on: cpu


In [5]:
# 텐서 연산(Operation)
if torch.cuda.is_available():
    tensor = tensor.to('cuda') # gpu가 존재하면 텐서 이동
tensor.device
torch.cuda.is_available()

False

In [6]:
# NumPy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print(tensor)
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[:, -1]}')
tensor[:, 1] = 0
print(tensor)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [26]:
# 산술 연산
tensor = torch.tensor([[1 ,0, 1],
                        [1, 0, 1],
                        [1, 0, 1],
                        [1, 0, 1]])
y1 = tensor @ tensor.T # 행렬곱
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

z1 = tensor * tensor # 요소별 곱
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor, dtype = torch.float)
torch.mul(tensor, tensor, out = z3) # 결과를 z3에 저장

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])

In [30]:
# 단일 요소 텐서의 데이터 타입 변환
agg = tensor.sum()
print(agg, type(agg)) # <class 'torch.Tensor'>
agg_item = agg.item()
print(agg_item, type(agg_item)) # <class 'int'>

tensor(8) <class 'torch.Tensor'>
8 <class 'int'>


In [34]:
# in-place 연산
print(tensor)
tensor.add(5)
print(tensor)
tensor.add_(5) # _(언더바)를 추가하면 값 자체를 변경함
print(tensor)
# 도함수 계산에 문제가 발생할 수 있으므로 사용을 권장하지 않음

tensor([[6, 5, 6],
        [6, 5, 6],
        [6, 5, 6],
        [6, 5, 6]])
tensor([[6, 5, 6],
        [6, 5, 6],
        [6, 5, 6],
        [6, 5, 6]])
tensor([[11, 10, 11],
        [11, 10, 11],
        [11, 10, 11],
        [11, 10, 11]])


In [41]:
# NumPy 변환
# 텐서를 nUMpY 배열로 변환
t = torch.ones(5)
n = t.numpy()
print(n, type(n)) # <class 'numpy.ndarray'>
# 텐서와 NumPy배열은 같은 메모리 공간을 공유하기 때문에 하나를 변경하면 다른 하나도 변경됨
t.add_(1)
print(t) # tensor([2., 2., 2., 2., 2.])
print(n) # [2. 2. 2. 2. 2.]
# NumPy배열을 텐서로 변환
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

np.add(n, 1, out = n)
print(n)
print(t)

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
