In [2]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
device = (
    'cuda'
    if torch.cuda.is_available()
    else 'mps'
    if torch.backends.mps.is_available()
    else 'cpu'
)
print(device)

cpu


In [7]:
class NeuralNetwork(nn.Module): # 파이토치의 모든 묘듈은 nn.Module의 하위 클래스. 신경망은 다른 모듈(계층)로 구성된 모듈. 이것이 중첩되어있는 구조임
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten() # 2D이미지 데이터를 1D벡터로 변환(평탄화)
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [36]:
X = torch.rand(1, 28, 28, device = device)
logits = model(X)
pred_prob = nn.Softmax(dim = 1)(logits)
y_pred = pred_prob.argmax(

    1)
print(y_pred)
print(model)
for name, param in model.named_parameters():
    print(name, param)


tensor([1])
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
linear_relu_stack.0.weight Parameter containing:
tensor([[ 0.0321, -0.0178, -0.0150,  ...,  0.0101,  0.0110,  0.0226],
        [ 0.0046, -0.0217, -0.0048,  ..., -0.0121, -0.0312, -0.0257],
        [-0.0184,  0.0240, -0.0040,  ..., -0.0052,  0.0062, -0.0210],
        ...,
        [-0.0216, -0.0014,  0.0216,  ...,  0.0270, -0.0239,  0.0105],
        [ 0.0136, -0.0194,  0.0002,  ...,  0.0042, -0.0258, -0.0236],
        [-0.0071, -0.0295,  0.0165,  ..., -0.0325,  0.0143,  0.0078]],
       requires_grad=True)
linear_relu_stack.0.bias Parameter containing:
tensor([ 0.0205,  0.0322,  0.0174, -0.0215, -0.0245, -0.0126,  0.0202, -0.0040,
        -0.0237, -0.0050,  0.018