In [5]:
# 역전파
# 가중치에 대한 손실의 변화율을 구하여 손실이 줄어드는 방향으로 가중치를 업데이트하는 방법
# 순전파로 출력 계산 > 손실 및 기울기 계산 > 가중치 업데이트 > 순전파 ... 반복하여 성능 이끌어냄
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad = True)
b = torch.randn(3, requires_grad = True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y) # Binary Classification에서 사용되는 손실함수
loss.backward()
print(w.grad)
print(b.grad)


tensor([[0.0856, 0.0149, 0.1530],
        [0.0856, 0.0149, 0.1530],
        [0.0856, 0.0149, 0.1530],
        [0.0856, 0.0149, 0.1530],
        [0.0856, 0.0149, 0.1530]])
tensor([0.0856, 0.0149, 0.1530])


In [18]:
# 역전파로 가중치 갱신 후 단순 예측만 할 때에도 기울기 추적을 하면 메모리가 낭비됨. 따라서 기울기 추적을 중단시킬 필요가 있음
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.inference_mode():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [23]:
inp = torch.eye(4, 5, requires_grad = True) # Identity Matrix 생성
'''
[[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0]]
'''
out = (inp + 1).pow(2).t()
'''
[[4, 1, 1, 1],
[1, 4, 1, 1],
[1, 1, 4, 1],
[1, 1, 1, 4],
[1, 1, 1, 1]]
'''
print(out)
out.backward(torch.ones_like(out), retain_graph = True)
print(inp.grad)
out.backward(torch.ones_like(out), retain_graph = True)
print(inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph = True)
print(inp.grad)

tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
